name: Merge main to deploy/preview on tag

on:
  push:
    tags:
      - "*"

jobs:
  merge-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name wjllance
          git config user.email wjllance@163.com

      - name: Set target branch and version
        id: set-branch
        run: |
          if [[ ${{ github.ref_name }} == *-prod ]]; then
            echo "TARGET_BRANCH=deploy" >> $GITHUB_ENV
            echo "IS_PREVIEW=false" >> $GITHUB_ENV
            # Extract version without -prod suffix
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/-prod$//')
          else
            echo "TARGET_BRANCH=preview" >> $GITHUB_ENV
            echo "IS_PREVIEW=true" >> $GITHUB_ENV
            VERSION="${{ github.ref_name }}"
          fi
          # Remove 'v' prefix if present
          VERSION=$(echo "$VERSION" | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Merge main into target branch
        run: |
          git checkout ${{ env.TARGET_BRANCH }}
          git merge origin/main --no-ff -m "Merge main into ${{ env.TARGET_BRANCH }} for tag ${{ github.ref_name }}"

      - name: Update package.json version
        run: |
          # Update version in package.json
          npm version ${{ env.VERSION }} --no-git-tag-version --allow-same-version
          # Stage and commit the version change
          git add package.json
          git commit -m "Update version to ${{ env.VERSION }} for tag ${{ github.ref_name }}"
          git push origin ${{ env.TARGET_BRANCH }}
